// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGConfigs
{
        public const string achievement_fast_mania = "CgkI-cHXz9EMEAIQDA"; // <GPGSID>
        public const string achievement_invert_picker = "CgkI-cHXz9EMEAIQBQ"; // <GPGSID>
        public const string achievement_gamer = "CgkI-cHXz9EMEAIQEg"; // <GPGSID>
        public const string achievement_magnet_mania = "CgkI-cHXz9EMEAIQCQ"; // <GPGSID>
        public const string achievement_magnet_picker = "CgkI-cHXz9EMEAIQAw"; // <GPGSID>
        public const string achievement_shield_picker = "CgkI-cHXz9EMEAIQAg"; // <GPGSID>
        public const string achievement_beginner = "CgkI-cHXz9EMEAIQEQ"; // <GPGSID>
        public const string achievement_shield_mania = "CgkI-cHXz9EMEAIQCA"; // <GPGSID>
        public const string achievement_magnet_upgrader = "CgkI-cHXz9EMEAIQDg"; // <GPGSID>
        public const string achievement_hide_mania = "CgkI-cHXz9EMEAIQDQ"; // <GPGSID>
        public const string achievement_hide_picker = "CgkI-cHXz9EMEAIQBw"; // <GPGSID>
        public const string achievement_invert_mania = "CgkI-cHXz9EMEAIQCw"; // <GPGSID>
        public const string achievement_master = "CgkI-cHXz9EMEAIQEw"; // <GPGSID>
        public const string achievement_slow_mania = "CgkI-cHXz9EMEAIQCg"; // <GPGSID>
        public const string achievement_slow_picker = "CgkI-cHXz9EMEAIQBA"; // <GPGSID>
        public const string leaderboard_rating = "CgkI-cHXz9EMEAIQAQ"; // <GPGSID>
        public const string achievement_fast_picker = "CgkI-cHXz9EMEAIQBg"; // <GPGSID>
        public const string achievement_shield_upgrader = "CgkI-cHXz9EMEAIQDw"; // <GPGSID>
        public const string achievement_eagle = "CgkI-cHXz9EMEAIQFA"; // <GPGSID>
        public const string achievement_slow_upgrader = "CgkI-cHXz9EMEAIQEA"; // <GPGSID>

}

